// frontend/js/app.js
// Structural Analysis Application - Frontend Controller

const API_URL = 'http://localhost:5000/api';

// State Management
let currentState = {
    beam: {
        // nodes generated by geometry; supports and loads are recorded separately
        nodes: [],
        elements: [],
        supports: [],      // { type, position }
        loads: [],         // { type, magnitude, position, end_position? }
        properties: { E: 200e9, I: 1e-4 }
    },
    frame: {
        nodes: [],
        elements: [],
        type: 'sway'
    },
    analysisResults: null
};

// Navigation
document.querySelectorAll('.nav-item').forEach(item => {
    item.addEventListener('click', () => {
        document.querySelectorAll('.nav-item').forEach(i => i.classList.remove('active'));
        item.classList.add('active');
        
        const section = item.dataset.section;
        document.querySelectorAll('.content-section').forEach(s => s.classList.remove('active'));
        document.getElementById(`${section}-section`).classList.add('active');
        
        // Update title
        const titles = {
            beam: 'Beam Structural Analysis',
            frame: '2D Frame Analysis',
            design: 'BS8110 Reinforcement Design',
            results: 'Results Database'
        };
        document.getElementById('page-title').textContent = titles[section];
    });
});

// Tab Switching
function switchTab(tabName) {
    document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(content => content.classList.remove('active'));
    
    event.target.classList.add('active');
    document.getElementById(`${tabName}-tab`).classList.add('active');
}

function showResultTab(tabName) {
    document.querySelectorAll('.res-tab').forEach(btn => btn.classList.remove('active'));
    document.querySelectorAll('.result-content').forEach(content => content.classList.remove('active'));
    
    event.target.classList.add('active');
    document.getElementById(`${tabName}-view`).classList.add('active');
}

// Beam Functions
function generateBeamNodes() {
    const length = parseFloat(document.getElementById('beam-length').value);
    const nElems = parseInt(document.getElementById('num-elements').value);

    currentState.beam.nodes = [];
    currentState.beam.elements = [];
    currentState.beam.supports = [];

    const spacing = length / nElems;

    // Create nodes
    for (let i = 0; i <= nElems; i++) {
        currentState.beam.nodes.push({
            id: i,
            x: i * spacing
        });
    }

    // create element connectivity
    for (let i = 0; i < nElems; i++) {
        currentState.beam.elements.push({
            id: i,
            node_i: i,
            node_j: i + 1
        });
    }

    // default support at left end for convenience
    if (currentState.beam.nodes.length > 0) {
        currentState.beam.supports.push({type: 'fixed', position: 0});
    }

    drawBeam();
    updateSupportsList();
}

function addSupport() {
    const type = document.getElementById('support-type').value;
    const pos = parseFloat(document.getElementById('support-pos').value);

    if (isNaN(pos)) {
        alert('Please enter a valid numeric position.');
        return;
    }

    const length = parseFloat(document.getElementById('beam-length').value);
    if (pos < 0 || pos > length) {
        alert('Support position is outside the beam length');
        return;
    }

    // if there's no existing node at that position, insert one and rebuild elements
    let node = currentState.beam.nodes.find(n => Math.abs(n.x - pos) < 1e-6);
    if (!node) {
        currentState.beam.nodes.push({ id: null, x: pos });
        currentState.beam.nodes.sort((a, b) => a.x - b.x);
        currentState.beam.nodes.forEach((n, i) => n.id = i);
        // rebuild element connectivity
        currentState.beam.elements = [];
        for (let i = 0; i < currentState.beam.nodes.length - 1; i++) {
            currentState.beam.elements.push({ id: i, node_i: i, node_j: i + 1 });
        }
        node = currentState.beam.nodes.find(n => Math.abs(n.x - pos) < 1e-6);
    }

    // record support entry (and also mark the node for clarity)
    currentState.beam.supports.push({ type, position: pos });
    node.support = type;

    updateSupportsList();
    drawBeam();
}


function updateSupportsList() {
    const container = document.getElementById('supports-list');
    container.innerHTML = currentState.beam.supports
        .map((s, idx) => `
            <div class="item-tag">
                <span>${s.type.toUpperCase()} at ${s.position.toFixed(2)}m</span>
                <button onclick="removeSupport(${idx})"><i class="fas fa-times"></i></button>
            </div>
        `).join('');
}

function removeSupport(index) {
    const removed = currentState.beam.supports.splice(index, 1)[0];
    // also clear any matching node flags
    const node = currentState.beam.nodes.find(n => Math.abs(n.x - removed.position) < 1e-6);
    if (node) {
        node.support = null;
        node.settlement = 0;
    }
    updateSupportsList();
    drawBeam();
}

function updateLoadForm() {
    const type = document.getElementById('load-type').value;
    const endGroup = document.getElementById('load-end-group');
    
    if (type === 'udl') {
        endGroup.classList.remove('hidden');
    } else {
        endGroup.classList.add('hidden');
    }
}

function addLoad() {
    const type = document.getElementById('load-type').value;
    const magnitude = parseFloat(document.getElementById('load-magnitude').value);
    const position = parseFloat(document.getElementById('load-position').value);

    if (isNaN(position)) {
        alert('Please enter a valid load position.');
        return;
    }
    const length = parseFloat(document.getElementById('beam-length').value);
    if (position < 0 || position > length) {
        alert('Load position is outside the beam range.');
        return;
    }

    const load = {
        type: type,
        magnitude: magnitude * 1000, // Convert to N
        position: position
    };

    if (type === 'udl') {
        const endPos = parseFloat(document.getElementById('load-end').value);
        if (isNaN(endPos) || endPos <= position) {
            alert('For UDL, end position must be greater than start.');
            return;
        }
        load.end_position = endPos;
    }

    currentState.beam.loads.push(load);
    updateLoadsList();
    drawBeam();
}

function updateLoadsList() {
    const container = document.getElementById('loads-list');
    container.innerHTML = currentState.beam.loads.map((l, idx) => `
        <div class="item-tag">
            <span>${l.type.toUpperCase()}: ${l.magnitude/1000}kN @ ${l.position.toFixed(2)}m</span>
            <button onclick="removeLoad(${idx})"><i class="fas fa-times"></i></button>
        </div>
    `).join('');
}

function removeLoad(index) {
    currentState.beam.loads.splice(index, 1);
    updateLoadsList();
    drawBeam();
}

// Canvas Drawing
function drawBeam() {
    const canvas = document.getElementById('beam-canvas');
    const ctx = canvas.getContext('2d');
    const width = canvas.width;
    const height = canvas.height;
    
    ctx.clearRect(0, 0, width, height);
    
    if (currentState.beam.nodes.length === 0) return;
    
    const maxX = Math.max(...currentState.beam.nodes.map(n => n.x));
    const scale = (width - 100) / maxX;
    const offsetY = height / 2;
    
    // Draw beam line
    ctx.beginPath();
    ctx.strokeStyle = '#94a3b8';
    ctx.lineWidth = 4;
    
    currentState.beam.nodes.forEach((node, i) => {
        const x = 50 + node.x * scale;
        if (i === 0) {
            ctx.moveTo(x, offsetY);
        } else {
            ctx.lineTo(x, offsetY);
        }
    });
    ctx.stroke();
    
    // Draw supports at nodes and at arbitrary positions
    const drawSupport = (type, xPos) => {
        const x = 50 + xPos * scale;
        const y = offsetY;
        ctx.fillStyle = '#2563eb';

        switch(type) {
            case 'fixed':
                ctx.fillRect(x - 4, y - 20, 8, 40);
                for (let i = -15; i < 15; i += 5) {
                    ctx.beginPath();
                    ctx.moveTo(x - 10, y + i);
                    ctx.lineTo(x + 10, y + i + 5);
                    ctx.stroke();
                }
                break;
            case 'pinned':
                ctx.beginPath();
                ctx.moveTo(x, y);
                ctx.lineTo(x - 10, y + 15);
                ctx.lineTo(x + 10, y + 15);
                ctx.closePath();
                ctx.fill();
                break;
            case 'roller':
                ctx.beginPath();
                ctx.arc(x, y + 10, 8, 0, Math.PI * 2);
                ctx.fill();
                break;
        }
    };

    currentState.beam.nodes.forEach(node => {
        if (node.support) {
            drawSupport(node.support, node.x);
        }
    });

    currentState.beam.supports.forEach(s => {
        drawSupport(s.type, s.position);
    });

    // show settlement arrows at any node with prescribed settlement
    currentState.beam.nodes.forEach(node => {
        if (node.settlement && node.settlement !== 0) {
            const x = 50 + node.x * scale;
            const y = offsetY;
            ctx.strokeStyle = '#ffb703';
            ctx.beginPath();
            ctx.moveTo(x, y);
            ctx.lineTo(x, y + 20);
            ctx.lineWidth = 2;
            ctx.stroke();
            ctx.beginPath();
            ctx.moveTo(x - 4, y + 16);
            ctx.lineTo(x, y + 20);
            ctx.lineTo(x + 4, y + 16);
            ctx.fillStyle = '#ffb703';
            ctx.fill();
        }
    });
    
    // Draw loads based on global positions
    currentState.beam.loads.forEach(load => {
        const x = 50 + load.position * scale;

        ctx.strokeStyle = '#ef4444';
        ctx.fillStyle = '#ef4444';

        if (load.type === 'point') {
            ctx.beginPath();
            ctx.moveTo(x, offsetY - 40);
            ctx.lineTo(x, offsetY);
            ctx.lineWidth = 2;
            ctx.stroke();

            ctx.beginPath();
            ctx.moveTo(x - 5, offsetY - 5);
            ctx.lineTo(x, offsetY);
            ctx.lineTo(x + 5, offsetY - 5);
            ctx.fill();
        } else if (load.type === 'udl') {
            const startX = x;
            const endX = 50 + load.end_position * scale;

            for (let px = startX; px <= endX; px += 20) {
                ctx.beginPath();
                ctx.moveTo(px, offsetY - 30);
                ctx.lineTo(px, offsetY);
                ctx.stroke();

                ctx.beginPath();
                ctx.moveTo(px - 3, offsetY - 3);
                ctx.lineTo(px, offsetY);
                ctx.lineTo(px + 3, offsetY - 3);
                ctx.fill();
            }
        }
    });
}

// helper to prepare beam payload, inserting nodes for supports and recomputing elements/loads
function buildBeamPayload() {
    const props = {
        E: currentState.beam.properties.E,
        I: currentState.beam.properties.I,
        A: currentState.beam.properties.A
    };

    // copy and sort original nodes
    let nodes = currentState.beam.nodes.map(n => ({
        id: n.id,
        x: n.x,
        support: null,
        settlement: n.settlement || 0
    }));
    nodes.sort((a, b) => a.x - b.x);
    nodes.forEach((n, i) => n.id = i);

    // incorporate supports (may create new node)
    currentState.beam.supports.forEach(s => {
        const existing = nodes.find(n => Math.abs(n.x - s.position) < 1e-6);
        if (existing) {
            existing.support = s.type;
        } else {
            nodes.push({id: null, x: s.position, support: s.type});
        }
    });

    // sort again and re-id
    nodes.sort((a, b) => a.x - b.x);
    nodes.forEach((n, i) => n.id = i);

    // build elements sequentially
    let elements = [];
    for (let i = 0; i < nodes.length - 1; i++) {
        elements.push({
            id: i,
            node_i: i,
            node_j: i + 1,
            ...props
        });
    }

    // convert loads to element-local coords
    let loads = [];
    currentState.beam.loads.forEach(l => {
        // find element containing this position
        let elemIndex = -1;
        for (let i = 0; i < nodes.length - 1; i++) {
            if (l.position >= nodes[i].x - 1e-6 && l.position <= nodes[i+1].x + 1e-6) {
                elemIndex = i;
                break;
            }
        }
        if (elemIndex === -1) return; // skip
        const localPos = l.position - nodes[elemIndex].x;
        const loadCopy = {
            type: l.type,
            magnitude: l.magnitude,
            element_id: elemIndex,
            position: localPos
        };
        if (l.end_position !== undefined) {
            loadCopy.end_position = l.end_position - nodes[elemIndex].x;
        }
        loads.push(loadCopy);
    });

    return { nodes, elements, loads };
}

// Analysis
async function runAnalysis() {
    showLoading(true);
    
    try {
        const payload = buildBeamPayload();
        
        const response = await fetch(`${API_URL}/analyze/beam`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        
        const data = await response.json();
        
        if (data.success) {
            currentState.analysisResults = data;
            displayResults(data);
        } else {
            alert('Analysis failed: ' + data.error);
        }
    } catch (error) {
        alert('Error: ' + error.message);
    } finally {
        showLoading(false);
    }
}

function displayResults(data) {
    // Show diagrams
    document.getElementById('result-plot').src = `data:image/png;base64,${data.plots}`;
    
    // Update tables
    const tbody = document.querySelector('#reactions-table tbody');
    tbody.innerHTML = data.reactions.map(r => `
        <tr>
            <td>${r.node}</td>
            <td>${r.position}</td>
            <td>${r.type}</td>
            <td>${r.vertical_force}</td>
            <td>${r.moment}</td>
            <td>${r.settlement ? (r.settlement*1000).toFixed(1) : '0.0'}</td>
        </tr>
    `).join('');
    
    // Update summary cards
    document.getElementById('max-moment').textContent = data.summary.max_moment.toFixed(2) + ' kNm';
    document.getElementById('max-shear').textContent = data.summary.max_shear.toFixed(2) + ' kN';
    document.getElementById('max-deflection').textContent = (data.summary.max_deflection * 1000).toFixed(2) + ' mm';
}

// BS8110 Design
async function runDesign() {
    if (!currentState.analysisResults) {
        alert('Please run structural analysis first');
        return;
    }
    
    const moment = currentState.analysisResults.summary.max_moment;
    const shear = currentState.analysisResults.summary.max_shear;
    
    const payload = {
        breadth: parseFloat(document.getElementById('section-b').value),
        depth: parseFloat(document.getElementById('section-d').value),
        moment: moment,
        shear: shear,
        is_sagging: true,
        fcu: parseInt(document.getElementById('concrete-grade').value),
        fy: parseInt(document.getElementById('steel-grade').value)
    };
    
    showLoading(true);
    
    try {
        const response = await fetch(`${API_URL}/design/bs8110`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        
        const data = await response.json();
        
        if (data.success) {
            displayDesignResults(data);
        }
    } catch (error) {
        alert('Design error: ' + error.message);
    } finally {
        showLoading(false);
    }
}

function displayDesignResults(data) {
    const design = data.design;
    const resultsDiv = document.getElementById('design-results');
    resultsDiv.classList.remove('hidden');
    
    document.getElementById('req-area').textContent = design.area_required_mm2 + ' mm²';
    document.getElementById('prov-reinf').textContent = design.main_reinforcement + 'T' + design.bar_diameter;
    document.getElementById('bar-spacing').textContent = design.spacing_mm + ' mm';
    document.getElementById('moment-cap').textContent = design.moment_capacity_kNm + ' kNm';
    document.getElementById('links-req').textContent = design.shear_links ? 'Yes' : 'No';
    document.getElementById('link-details').textContent = design.shear_links ? 
        `T${design.link_diameter} @ ${design.link_spacing}mm c/c` : 'Not required';
    
    document.getElementById('util-value').textContent = design.utilization_percent + '%';
    document.getElementById('crack-value').textContent = design.crack_width_mm + ' mm';
    
    // Update visual
    document.getElementById('tension-reinf-visual').textContent = 
        `${design.main_reinforcement}T${design.bar_diameter}`;
}

// Standalone BS8110 Design
async function runBS8110Design() {
    const payload = {
        breadth: parseFloat(document.getElementById('bs8110-b').value),
        depth: parseFloat(document.getElementById('bs8110-d').value),
        moment: parseFloat(document.getElementById('bs8110-m').value),
        shear: parseFloat(document.getElementById('bs8110-v').value),
        fcu: parseInt(document.getElementById('bs8110-fcu').value),
        fy: parseInt(document.getElementById('bs8110-fy').value),
        is_sagging: document.getElementById('bs8110-type').value === 'true'
    };
    
    showLoading(true);
    
    try {
        const response = await fetch(`${API_URL}/design/bs8110`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        
        const data = await response.json();
        
        if (data.success) {
            displayBS8110Results(data);
        }
    } catch (error) {
        alert('Error: ' + error.message);
    } finally {
        showLoading(false);
    }
}

function displayBS8110Results(data) {
    const results = document.getElementById('bs8110-results');
    results.classList.remove('hidden');
    
    const design = data.design;
    
    // Update calculations
    document.getElementById('calc-k').textContent = (design.moment * 1e6 / 
        (parseInt(document.getElementById('bs8110-fcu').value) * 
         parseInt(document.getElementById('bs8110-b').value) * 
         Math.pow(parseInt(document.getElementById('bs8110-d').value), 2))).toFixed(4);
    
    document.getElementById('calc-as').textContent = design.area_required_mm2 + ' mm²';
    document.getElementById('calc-v').textContent = (parseFloat(document.getElementById('bs8110-v').value) * 1000 / 
        (parseInt(document.getElementById('bs8110-b').value) * 
         parseInt(document.getElementById('bs8110-d').value))).toFixed(3) + ' N/mm²';
    
    // Update results
    document.getElementById('res-provided').textContent = `${design.main_reinforcement}T${design.bar_diameter}`;
    document.getElementById('res-area').textContent = design.area_provided_mm2 + ' mm²';
    document.getElementById('res-spacing').textContent = design.spacing_mm + ' mm';
    
    document.getElementById('calc-links').textContent = design.shear_links ? 
        `T${design.link_diameter} @ ${design.link_spacing}mm c/c` : 'Not required';
    
    // Update checks
    const utilBar = document.getElementById('util-bar');
    utilBar.style.width = Math.min(design.utilization_percent, 100) + '%';
    utilBar.style.background = design.utilization_percent > 90 ? 'var(--warning)' : 'var(--success)';
    document.getElementById('util-text').textContent = design.utilization_percent + '%';
    
    document.getElementById('crack-result').textContent = design.crack_width_mm + ' mm';
    document.getElementById('crack-result').style.color = design.crack_width_mm > 0.3 ? 'var(--danger)' : 'var(--success)';
    
    // Status
    const status = document.getElementById('design-status');
    status.textContent = design.utilization_percent <= 100 && design.crack_width_mm <= 0.3 ? 'PASS' : 'REVIEW';
    status.className = 'status-badge ' + (design.utilization_percent <= 100 && design.crack_width_mm <= 0.3 ? 'pass' : 'fail');
}

// Frame Functions
function generateFrame() {
    const storeys = parseInt(document.getElementById('frame-storeys').value);
    const bays = parseInt(document.getElementById('frame-bays').value);
    const h = parseFloat(document.getElementById('storey-height').value);
    const w = parseFloat(document.getElementById('bay-width').value);
    
    // Generate nodes
    currentState.frame.nodes = [];
    currentState.frame.elements = [];
    
    let nodeId = 0;
    for (let storey = 0; storey <= storeys; storey++) {
        for (let bay = 0; bay <= bays; bay++) {
            const support = storey === 0 ? 'fixed' : 'free';
            currentState.frame.nodes.push({
                id: nodeId++,
                x: bay * w,
                y: storey * h,
                support: support
            });
        }
    }
    
    // Generate elements (columns and beams)
    let elemId = 0;
    const nCols = bays + 1;
    
    // Columns
    for (let col = 0; col < nCols; col++) {
        for (let storey = 0; storey < storeys; storey++) {
            const bottomNode = storey * nCols + col;
            const topNode = (storey + 1) * nCols + col;
            currentState.frame.elements.push({
                id: elemId++,
                node_i: bottomNode,
                node_j: topNode
            });
        }
    }
    
    // Beams
    for (let storey = 1; storey <= storeys; storey++) {
        for (let bay = 0; bay < bays; bay++) {
            const leftNode = storey * nCols + bay;
            const rightNode = storey * nCols + bay + 1;
            currentState.frame.elements.push({
                id: elemId++,
                node_i: leftNode,
                node_j: rightNode
            });
        }
    }
    
    drawFrame();
}

function drawFrame() {
    const canvas = document.getElementById('frame-canvas');
    const ctx = canvas.getContext('2d');
    
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    
    if (currentState.frame.nodes.length === 0) return;
    
    const maxX = Math.max(...currentState.frame.nodes.map(n => n.x));
    const maxY = Math.max(...currentState.frame.nodes.map(n => n.y));
    
    const scaleX = (canvas.width - 100) / maxX;
    const scaleY = (canvas.height - 100) / maxY;
    const scale = Math.min(scaleX, scaleY);
    
    const offsetX = 50;
    const offsetY = canvas.height - 50;
    
    // Draw elements
    ctx.strokeStyle = '#94a3b8';
    ctx.lineWidth = 3;
    
    currentState.frame.elements.forEach(elem => {
        const nodeI = currentState.frame.nodes[elem.node_i];
        const nodeJ = currentState.frame.nodes[elem.node_j];
        
        ctx.beginPath();
        ctx.moveTo(offsetX + nodeI.x * scale, offsetY - nodeI.y * scale);
        ctx.lineTo(offsetX + nodeJ.x * scale, offsetY - nodeJ.y * scale);
        ctx.stroke();
    });
    
    // Draw nodes
    currentState.frame.nodes.forEach(node => {
        const x = offsetX + node.x * scale;
        const y = offsetY - node.y * scale;
        
        if (node.support === 'fixed') {
            ctx.fillStyle = '#2563eb';
            ctx.fillRect(x - 6, y - 6, 12, 12);
        } else {
            ctx.fillStyle = '#64748b';
            ctx.beginPath();
            ctx.arc(x, y, 4, 0, Math.PI * 2);
            ctx.fill();
        }
    });
}

async function runFrameAnalysis() {
    const payload = {
        analysis_type: document.getElementById('frame-type').value,
        nodes: currentState.frame.nodes,
        elements: currentState.frame.elements,
        loads: [] // Add load collection similar to beam
    };
    
    showLoading(true);
    
    try {
        const response = await fetch(`${API_URL}/analyze/frame`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        
        const data = await response.json();
        
        if (data.success) {
            document.getElementById('frame-plot').src = `data:image/png;base64,${data.plot}`;
            
            // Update tables
            const forcesBody = document.querySelector('#member-forces-table tbody');
            forcesBody.innerHTML = data.member_forces.map(m => `
                <tr>
                    <td>${m.element}</td>
                    <td>${m.axial_i.toFixed(2)}</td>
                    <td>${m.shear_i.toFixed(2)}</td>
                    <td>${m.moment_i.toFixed(2)}</td>
                </tr>
            `).join('');
            
            const dispBody = document.querySelector('#nodal-disp-table tbody');
            dispBody.innerHTML = data.nodal_results.map(n => `
                <tr>
                    <td>${n.node}</td>
                    <td>${(n.displacement_x * 1000).toFixed(2)}</td>
                    <td>${(n.displacement_y * 1000).toFixed(2)}</td>
                    <td>${n.rotation.toFixed(6)}</td>
                </tr>
            `).join('');
        }
    } catch (error) {
        alert('Frame analysis error: ' + error.message);
    } finally {
        showLoading(false);
    }
}

// Utilities
function showLoading(show) {
    document.getElementById('loading-overlay').classList.toggle('hidden', !show);
}

function clearAll() {
    currentState.beam = { 
        nodes: [], 
        elements: [], 
        supports: [], 
        loads: [], 
        properties: { E: 200e9, I: 1e-4, A: 0.01 }
    };
    currentState.frame = { nodes: [], elements: [], type: 'sway' };
    currentState.analysisResults = null;
    
    document.querySelectorAll('.item-list').forEach(el => el.innerHTML = '');
    document.querySelectorAll('canvas').forEach(c => {
        const ctx = c.getContext('2d');
        ctx.clearRect(0, 0, c.width, c.height);
    });
    
    document.getElementById('result-plot').src = '';
}

function exportReport() {
    alert('Report export functionality would generate PDF with all calculations and diagrams');
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    generateBeamNodes();
});